import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.jsx';
import { api } from '../lib/api.js';

const today = new Date().toISOString().split('T')[0];

function formatDate(isoDate) {
  if (!isoDate) return '';
  const [y, m, d] = isoDate.split('-');
  return `${parseInt(m, 10)}/${parseInt(d, 10)}/${y}`;
}

export default function Reservation() {
  const [validated, setValidated] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [modalView, setModalView] = useState('details'); // 'details' | 'success'
  const [confirming, setConfirming] = useState(false);
  const [confirmError, setConfirmError] = useState('');
  const [savedReservation, setSavedReservation] = useState(null);
  const [form, setForm] = useState({
    name: '', phone: '', email: '', guests: '', date: '', time: '', note: '',
  });
  const { isAuthenticated, token } = useAuth();
  const navigate = useNavigate();

  function update(field, value) {
    setForm((f) => ({ ...f, [field]: value }));
  }

  function handlePhoneInput(e) {
    update('phone', e.target.value.replace(/[^0-9+\-\s]/g, ''));
  }

  function handleSubmit(e) {
    e.preventDefault();
    const el = e.target;
    if (el.checkValidity() === false) {
      e.stopPropagation();
      setValidated(true);
      return;
    }
    setValidated(false);
    if (!isAuthenticated) {
      navigate('/login', { state: { from: { pathname: '/reservation' } } });
      return;
    }
    setConfirmError('');
    setModalView('details');
    setShowConfirm(true);
  }

  function handleBackToEdit() {
    setShowConfirm(false);
  }

  /**
   * Submits the reservation to POST /api/reservations. The booking
   * reference (e.g. RSV-482913) is generated by the server, not the
   * client, so it's only known once this succeeds.
   */
  async function handleConfirmBooking() {
    setConfirming(true);
    setConfirmError('');
    try {
      const reservation = await api.createReservation(token, {
        name: form.name,
        phone: form.phone,
        email: form.email || undefined,
        guests: form.guests,
        date: form.date,
        time: form.time,
        note: form.note || undefined,
      });
      setSavedReservation(reservation);
      setModalView('success');
    } catch (err) {
      setConfirmError(err.message || 'Could not confirm your reservation. Please try again.');
    } finally {
      setConfirming(false);
    }
  }

  function handleCloseAfterSuccess() {
    setShowConfirm(false);
    setForm({ name: '', phone: '', email: '', guests: '', date: '', time: '', note: '' });
    setSavedReservation(null);
  }

  function handleOverlayOrClose() {
    if (modalView === 'success') {
      handleCloseAfterSuccess();
    } else {
      handleBackToEdit();
    }
  }

  return (
    <>
      <header className="page-header">
        <div className="container">
          <div className="breadcrumb-ticket mb-2"><Link to="/">Home</Link><span className="sep">/</span>Reservation</div>
          <h1>Book a Table</h1>
        </div>
      </header>

      <section>
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              <div className="ticket-card">
                <form className={`needs-validation${validated ? ' was-validated' : ''}`} noValidate onSubmit={handleSubmit}>
                  <div className="row g-3">
                    <div className="col-md-6">
                      <label htmlFor="resName" className="form-label">Name</label>
                      <input type="text" className="form-control" id="resName" required minLength={2}
                        value={form.name} onChange={(e) => update('name', e.target.value)} />
                      <div className="invalid-feedback">Please enter your name.</div>
                    </div>
                    <div className="col-md-6">
                      <label htmlFor="resPhone" className="form-label">Phone</label>
                      <input type="tel" className="form-control" id="resPhone" pattern="[0-9+\-\s]{7,15}" required
                        value={form.phone} onChange={handlePhoneInput} />
                      <div className="invalid-feedback">Please enter a valid phone number (7&ndash;15 digits).</div>
                    </div>
                    <div className="col-md-6">
                      <label htmlFor="resEmail" className="form-label">Email</label>
                      <input type="email" className="form-control" id="resEmail" required
                        value={form.email} onChange={(e) => update('email', e.target.value)} />
                      <div className="invalid-feedback">Please enter a valid email address.</div>
                    </div>
                    <div className="col-md-6">
                      <label htmlFor="resGuests" className="form-label">Guests</label>
                      <select className="form-select" id="resGuests" required
                        value={form.guests} onChange={(e) => update('guests', e.target.value)}>
                        <option value="">Choose...</option>
                        <option>1 Guest</option>
                        <option>2 Guests</option>
                        <option>3&ndash;4 Guests</option>
                        <option>5&ndash;8 Guests</option>
                        <option>9+ Guests</option>
                      </select>
                      <div className="invalid-feedback">Please select the number of guests.</div>
                    </div>
                    <div className="col-md-6">
                      <label htmlFor="resDate" className="form-label">Date</label>
                      <input type="date" className="form-control" id="resDate" required min={today}
                        value={form.date} onChange={(e) => update('date', e.target.value)} />
                      <div className="invalid-feedback">Please choose a valid date.</div>
                    </div>
                    <div className="col-md-6">
                      <label htmlFor="resTime" className="form-label">Time</label>
                      <input type="time" className="form-control" id="resTime" required
                        value={form.time} onChange={(e) => update('time', e.target.value)} />
                      <div className="invalid-feedback">Please choose a time.</div>
                    </div>
                    <div className="col-12">
                      <label htmlFor="resNote" className="form-label">Special Request</label>
                      <textarea className="form-control" id="resNote" rows={3} placeholder="Allergies, occasions, seating preference..."
                        value={form.note} onChange={(e) => update('note', e.target.value)} />
                    </div>
                    <div className="col-12 text-center mt-4">
                      <button type="submit" className="btn btn-ember btn-lg px-5">Book Now</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>

      <div className={`confirm-modal-overlay${showConfirm ? ' open' : ''}`} onClick={handleOverlayOrClose}>
        <div className="confirm-modal" onClick={(e) => e.stopPropagation()}>
          <div className="confirm-modal-header">
            <h3>Your Reservation</h3>
            <button type="button" className="confirm-modal-close" aria-label="Close" onClick={handleOverlayOrClose}>&times;</button>
          </div>

          {modalView === 'details' && (
            <>
              <div className="confirm-box">
                <div className="confirm-row"><span>Name</span><span>{form.name}</span></div>
                <div className="confirm-row"><span>Phone</span><span>{form.phone}</span></div>
                <div className="confirm-row"><span>Date</span><span>{formatDate(form.date)}</span></div>
                <div className="confirm-row"><span>Time</span><span>{form.time}</span></div>
                <div className="confirm-row"><span>Guests</span><span>{form.guests}</span></div>
                {form.note && (
                  <>
                    <hr />
                    <div className="confirm-row"><span>Notes</span><span>{form.note}</span></div>
                  </>
                )}
              </div>

              {confirmError && <div className="auth-error mt-3">{confirmError}</div>}

              <div className="confirm-modal-actions">
                <button type="button" className="btn btn-ember btn-lg w-100 justify-content-center" onClick={handleConfirmBooking} disabled={confirming}>
                  {confirming ? 'Confirming…' : 'Confirm & Book Table'}
                </button>
                <button type="button" className="btn btn-outline-ink btn-lg w-100 justify-content-center" onClick={handleBackToEdit} disabled={confirming}>Back to Edit</button>
              </div>
            </>
          )}

          {modalView === 'success' && savedReservation && (
            <div className="invoice-success">
              <div className="check-circle">&#10003;</div>
              <h5 className="mb-2">Table Reserved!</h5>
              <p className="text-muted mb-1">
                Thank you, {savedReservation.name}. We&rsquo;ve saved your table for {formatDate(savedReservation.date)} at {savedReservation.time?.slice(0, 5)}. See you soon!
              </p>
              <p className="text-muted mb-0"><strong>Booking Ref #{savedReservation.booking_ref}</strong></p>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
